name: Debug
on:
    pull_request
jobs:
    output-debug:
        runs-on: ubuntu-latest
        steps:
            - uses: mramsey24/github-action-explore-debug@main
              with:
                jq_selector: ".pull_request"
